tmp_res<32> := 0x50000000

replace <br_i31_sub>(sub_a, sub_b, sub_ctl) by  # br_i31_sub
		#sub_a_glo := sub_a

		#print sub_ctl
		
		#print @[sub_a, 4]
		#print (((@[sub_a, 4] + 63) lsr 5)-1)
		#print @[sub_a+4, 68]
		
		#print @[sub_b, 4]
		#print ((@[sub_b, 4] + 63) lsr 5)
		#print @[sub_b+4, 68]
		
		
		pushBN sub_a
		pushBN sub_b
		subBN
		popBN tmp_res
		@[sub_a+4, 132] := sub_ctl = 0 ? @[sub_a+4, 132] : @[tmp_res+4, 132]

		#print @[sub_a+4, 68]
		#print carry32<32>
		
		return carry32
end
