replace <mbedtls_mpi_shift_l>(shl_X, shl_count) by
	# X = X << count (left shift)
	# X is mbedtls_mpi structure pointer
	# count is number of bits to shift

	print shl_X
	print shl_count

	pushBN shl_X
	shl_count_bv<2048> := uext2048 shl_count
	pushBV shl_count_bv
	leftShiftBN

	popBN shl_X

	print shl_X

	return 0
end
