# base_addr<32> := 0x18700000

def_macro mk_safe(p)
          #print base_addr
          @[p+4,4] := @[p,4] = 0x0 ? 0x0 : @[p+4,4]
	  @[p+8,4] := @[p,4] = 0x0 ? 0x10 : @[p+8,4]
	  @[p+12,4] := @[p,4] = 0x0 ? 0 : @[p+12,4]
	  @[p,4] := @[p,4] = 0x0 ? base_addr : @[p,4]
          
	  base_addr := base_addr + 0x100
end


def_macro mk_d_safe(p)
          #print base_addr
          @[base_addr,0x100] := @[@[p,4],0x100]
          @[p,4] := base_addr
	  base_addr := base_addr + 0x100
end
