replace <br_i31_decode>(dec_x, dec_src, dec_len) by
	# print dec_len
	print @[dec_src, 0x100]
	dec_buf<32> := 0x2fff0000
	
	# bit_len<32> := dec_len - 132
    	# Reverse bytes for big-endian input
    	for i<32> in 0 to 131 do
        	byte_idx<32> := dec_len - 1 - i
        	@[dec_buf + i] := i < dec_len ? @[dec_src+byte_idx] : 0
    	end
    	
    	decbvx<1056> := @[dec_buf, 132] 
    	print decbvx
    	
	pushBV decbvx
	popBN dec_x
	return 0
end
