
replace <sp_exptmod_nct>(exm_b, exm_e, exm_m, exm_r) by
	print exm_b
	print exm_e
	print exm_m
	print exm_r
	@[exm_m+8,1] := @[exm_m+8,1] & 0xfe
	print @[exm_b,5]
	print @[exm_e,5]
	print @[exm_m,5]
        print @[exm_b+8,0x100]
        print @[exm_e+8,0x100]
        print @[exm_m+8,0x100]
    
        if exm_b = 0 || exm_e = 0 || exm_m = 0 || exm_r = 0 then
        	return -98
        end
        
        pushBN exm_m
        popBV exm_m_bv<2056>
    	exm_m_bv<2056> := (@[exm_m,2] = 0 || @[exm_m+4,1] = 1 ? 1 : exm_m_bv)
    	
    	pushBN exm_b
        popBV exm_b_bv<2056>
    
        pushBN exm_e
        popBV exm_e_bv<2056>
        
        #exm_b_bv := 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        #exm_m_bv := 0x1bbbbbbbbbbbbbbc
        #exm_e_bv := 0x1
        
        # b%m * b%m * b%m * b%m * b%m
        # 5555555555555555 * 5555555555555555 * 5555555555555555 * 5555555555555555 * 5555555555555555
        # 1111111111111111
        
        print exm_b_bv
        print exm_e_bv
        print exm_m_bv
        
        
        
        exm_b_bv_x<4112> := uext4112 exm_b_bv
        exm_e_bv_x<4112> := uext4112 exm_e_bv
        exm_m_bv_x<4112> := uext4112 exm_m_bv
        
    	exm_result<4112> := 1
    	exm_base<4112> := exm_b_bv_x % exm_m_bv_x
    	exm_num_bits<4112> := uext4112 (@[exm_e,2] * 32)
    	print exm_num_bits
    	# Process bits from LSB to MSB (naturally upward)
    	for i4112<4112> in 0 to 16 do
    		#print i2056
        	# Extract bit i from LSB (right shift by i, take LSB)
        	exm_bit_i<4112> := (exm_e_bv_x lsr i4112) & 0x1
        
        	# Conditional multiply (constant-time)
        	exm_temp<4112> := (exm_result * exm_base) % exm_m_bv_x
        	
        	print exm_temp
        	print exm_result
        	print exm_base
        	print exm_m_bv_x
        	
        	# exm_result := (exm_bit_i = 1) ? ((i4112 < exm_num_bits) ? exm_temp : exm_result) : exm_result
        	exm_result := (exm_bit_i = 1) ? exm_temp : exm_result
        	
        	
        	print exm_result{2047..0}
        	# Square base for next iteration
        	exm_base := (exm_base * exm_base) % exm_m_bv_x
    	end
    
    	exm_result_y<2056> := exm_result{2055..0}
    	print exm_result_y
        pushBV exm_result_y
        popBN exm_r
        
        return 0
end


