replace <sp_add>(add_a, add_b, add_r) by
        pushBN add_a
        pushBN add_b
        addBN
        popBN add_r
        
        print @[add_b+8, 0x40]
        print @[add_a+8, 0x40]
	print add_r
	print @[add_r,2]
        print @[add_r+8, 0x40]
        return 0
end

replace <_sp_add_d>(add_a, add_d, add_r) by
        pushBN add_a
        add_d_bv<512> := uext512 add_d
        pushBV add_d_bv
        addBN
        popBN add_r
        
        print @[add_b+8, 0x40]
        print @[add_a+8, 0x40]
	print add_r
	print @[add_r,2]
        print @[add_r+8, 0x40]

        return 0
end

replace <sp_add_d>(add_a, add_d, add_r) by
	# CROSS CHECKED
        pushBN add_a
        add_d_bv<512> := uext512 add_d
        pushBV add_d_bv
        addBN
        popBN add_r
        
        
        print @[add_a+8, 0x40]
	print add_d
	print add_r
	print @[add_r,2]
        print @[add_r+8, 0x40]

        return 0
end

replace <_sp_add_off>(add_a, add_b, add_r, add_o) by
        pushBN add_a
        pushBN add_b
        add_o_bv<512> := uext512 (add_o * 4)
        pushBV add_o_bv
        leftShiftBN
        addBN
        popBN add_r
        
        print @[add_b+8, 0x40]
        print @[add_a+8, 0x40]
	print add_r
	print @[add_r,2]
        print @[add_r+8, 0x40]

        return 0	
end
