hook <wc_ecc_sign_hash>(_, _, _, _, _, hash_ecc) with
#	print @[@[<ecc_k>, 4], 32]
	@[hash_ecc+3144, 32] := secret
#	print @[hash_ecc+3144, 32] 
	
#	
end

#@[<len_ecc_k>, 4] := 32
#@[@[<ecc_k>, 4], 32] := secret # as skey
#assume skey > (0x1 lsl 255)



