@[@[<eddsa_private_key>, 4], 32] := secret

#hook 0x565d32c8 with
#	@[esp, 8] := @[eax, 8]
#	jump at 0x565d32cd
#end



#replace 0x565d32c0(al_val, al_ret, _) by
#        @[al_ret,8] := @[al_val,8]
#        return 1
#end

#replace 0x565d32e0(al_val, al_ret, _) by
#        @[al_ret,8] := @[al_val,8]
#        return 1
#end

#hook <ed25519_digest_sign>(sign_vpeddsactx, _) with
#     print sign_vpeddsactx
#     sign_key<32> := @[sign_vpeddsactx+4, 4]
#     print sign_key
#     print @[sign_key, 64]
#     print @[sign_key+44, 4]
     #priv_key<32> := @[sign_key+44, ]
     
     
     #print priv_key
     #print @[priv_key, 32]
     #@[priv_key, 32] := secret
#end

#hook <ossl_ed25519_sign>(sign,out, sign_tbs, sign_len, sign_pub, sign_priv, _) with
#     @[sign_priv, 32] := secret
#end
