hook <wc_ed25519_sign_msg>(ed_in, ed_inlen, _, _, ed_key) with
	@[ed_in, 0x20] := nondet
	ed_inlen := nondet
	rsi<32> := nondet
	#print ed_key
	#print @[ed_key+0x20, 0x20]
	#@[ed_key+0x20, 0x20] := secret
	#print @[ed_key+0x20, 0x20] 
	
	# here the induced memory access leak is caught (for testing). So, tainting is working
	#@[base_addr+@[ed_key+0x20, 0x4]] := 80
end

@[<len_eddsa_private_key>, 4] := 64
@[@[<eddsa_private_key>, 4], 32] := secret # as skey
@[@[<eddsa_private_key>, 4]+32, 32] := nondet
#assume skey > (0x1 lsl 255)


hook <ed25519_hash_update>(ed_key, _) with
	#print ed_key
	#print @[ed_key+0x20, 0x20]
	#@[ed_key+0x20, 0x20] := secret
	#print @[ed_key+0x20, 0x20] 
	
	# here the induced memory access leak is caught (for testing). So, tainting is working
	#@[base_addr+@[ed_key+0x20, 0x4]] := 80
	
end

