
glo_rnd_buf<32> := 0
replace <custom_rng>(_, rnd_buf, rnd_num) by
        # glo_rnd_buf := rnd_buf
        print rnd_buf
	for rand_i<32> in 0 to (rnd_num-1) do
		@[rnd_buf+rand_i, 4] := secret
	end
        return 0
        
end

