#@[@[<rsa_d>, 4], 0x100] := secret as rsa_dd
#@[@[<rsa_p>, 4], 0x80] := secret as rsa_pp
#@[@[<rsa_q>, 4], 0x80] := secret as rsa_qq
#@[@[<rsa_dp>, 4], 0x80] := secret as rsa_dmp11
#@[@[<rsa_dq>, 4], 0x80] := secret as rsa_dmq11
#@[@[<rsa_qp>, 4], 0x80] := secret as rsa_iqmpp	

# assume rsa_dd>0
# assume rsa_pp>0
# assume rsa_qq>0
# assume rsa_dmp11>0
# assume rsa_dmp11>0
# assume rsa_iqmpp>0

hook <mbedtls_rsa_pkcs1_decrypt>(mbctx, _) with
	@[@[mbctx+20,4], 0x100] := secret
	@[@[mbctx+28,4], 0x80] := secret
	@[@[mbctx+36,4], 0x80] := secret
	@[@[mbctx+44,4], 0x80] := secret
	@[@[mbctx+52,4], 0x80] := secret
	@[@[mbctx+60,4], 0x80] := secret
	
end
