@[@[<rsa_p>, 4], 0x80] := secret #secret
@[@[<rsa_q>, 4], 0x80] := secret
@[@[<rsa_dp>, 4], 0x80] := secret
@[@[<rsa_dq>, 4], 0x80] := secret
@[@[<rsa_iq>, 4], 0x80] := secret

#hook <rsa_decrypt_pkcs1_v15>(dec_in, _) with
#	@[dec_in, 0x20] := nondet
#end

#hook <rsa_sign_pkcs1_v15>(sign_in, _) with
#	@[sign_in, 0x20] := nondet
#end

