# BN_mul - Multiplication (compact version)
# Computes: r = a * b

replace <BN_mul>(mul_r, mul_a, mul_b, _) by # BN_mul
	# r = a * b
	pushBN mul_a
	pushBN mul_b
	mulBN
	popBN mul_r

	return 1
end

replace <bn_mul_fixed_top>(fmul_r, fmul_a, fmul_b, _) by # bn_mul_fixed_top
	# r = a * b
	pushBN fmul_a
	popBV fmul_a_bv<2056>
	pushBN fmul_b
	popBV fmul_b_bv<2056>
	
	print fmul_a_bv
	print fmul_b_bv
	fmul_a_bv_ex<5112> := uext5112 fmul_a_bv
	fmul_b_bv_ex<5112> := uext5112 fmul_b_bv
	fmul_r_bv_ex<5112> := fmul_a_bv_ex * fmul_b_bv_ex
	print fmul_r_bv_ex
	fmul_r_bv<2056> := fmul_r_bv_ex{2055..0}
	print fmul_r_bv
	# mulBN
	pushBV fmul_r_bv
	popBN fmul_r
	
	return 1
end
