tmp_res<32> := 0x40000000

replace <br_i31_montymul>(mul_d, mul_x, mul_y, mul_m, m0i) by  # br_i31_add
		pushBN mul_x
		popBV  bv_xx<1056>
		pushBN mul_y
		popBV  bv_yy<1056>
		pushBN mul_m
		popBV  bv_mm<1056>

		bv_m<512> := bv_mm{511..0}
		bv_x<512> := bv_xx{511..0}
		bv_y<512> := bv_yy{511..0}
		# Constants
    # R_BITS<32> := 32
    R<64> := 1 lsl 32 # R = 2^32

    # Compute t = x * y (2048-bit multiplication)
    t<1056> := (uext1056 bv_x) * (uext1056 bv_y)

    # Compute t0 = t mod R
    #t0<32> := 

    # Compute f = (t0 * m0i) mod R
    f<32> := (((uext64 t{31..0}) * (uext64 m0i)) & 0xFFFFFFFF){31..0};

    # Compute s = t + f * m
    s<1056> := t + (uext1056 f) * (uext1056 bv_m);

    # Compute u = s / R (shift right by 32 bits)
    u<1056> := s lsr 32

    # If u >= m, subtract m
		u := u >= m ? u-m: u

    # Set the result
    bv_d<1056> := u

		pushBV bv_d
		popBN mul_d
		
		@[mul_d,4] := @[mul_x,4]
		
		return 0
end

