replace <br_i31_muladd_small>(mas_x, mas_z, mas_m) by
	mas_mbl<32> := @[mas_m, 4]
	pushBN mas_x
	popBV mas_bvx<1056>
	pushBN mas_m
	popBV mas_bvm<1056>
	# x = (x * 2^31 + z) mod m
	mas_bvx := (mas_bvx lsl 31) | (uext1056 mas_z)
	mas_bvm_safe<1056> := mas_bvm = 0 ? 1 : mas_bvm
	mas_bvx := mas_mbl = 0 ? mas_bvx : mas_bvx % mas_bvm_safe
	pushBV mas_bvx
	popBN mas_x
	return 0
end
