#replace <sp_read_unsigned_bin>(read_a, read_in, read_inSz) by
#        @[read_a,2] := read_inSz{15..0} / 4
#        @[read_a+2,2] := 257
#        @[read_a+4,1] := 0
#        for i<32> in 0 to read_inSz - 1 do
#            @[read_a+8+i,1] := @[read_in+read_inSz-i-1, 1]
#        end
#        return 0
#end

replace <sp_read_unsigned_bin>(read_a, read_in, read_inSz) by
        print read_inSz
        print @[read_in, 4]
        print @[read_in+read_inSz-4, 4]
        
        
        bv_tmp<512> := 0
        
        if read_inSz = 3 then
        	bv_tmp := uext512 @[read_in, 3]
        else 
        	if read_inSz = 0x20 then
        		bv_tmp := uext512 @[read_in, 0x20]
        	else
        		if read_inSz = 0x40 then
        			bv_tmp := @[read_in, 0x40]
        		else
        			read_tmp<32> := 0x6f000000
        			@[read_tmp, 128] := 0
        			for i<32> in 0 to 255 do
        			    @[read_tmp+i,1] := (i<read_inSz ? @[read_in+read_inSz-i-1, 1] : 0)
        			end
        			bv_tmp := @[read_tmp, 64]
        		end
        	end
        end

        print bv_tmp{511..0}
        
        
        pushBV bv_tmp
        popBN read_a

        print @[read_a, 2]
        print @[read_a+2, 2]
        print @[read_a+4, 1]
        print @[read_a+8, 4]
        print @[read_a+8+read_inSz-4, 4]
        return 0
end
