replace <sp_sub>(sub_a, sub_b, sub_r) by
	# CROSS CHECKED
	print sub_a
	print sub_b
	print @[sub_a,5]
	print @[sub_b,5]
	print @[sub_a+8, 0x20]
	print @[sub_b+8, 0x20]
	
        pushBN sub_a
        pushBN sub_b
        subBN
        popBN sub_r
        
        print sub_r
        print @[sub_r, 5]
        print @[sub_r+8, 0x40]
        
        return 0
end
