replace <mbedtls_mpi_mod_mpi>(mod_R, mod_A, mod_N) by
	# R = A mod N
	# R, A, N are mbedtls_mpi structure pointers

	print mod_A
	print mod_N

	pushBN mod_A
	popBV mod_A_bv<2048>

	pushBN mod_N
	popBV mod_N_bv<2048>

	# Modulo operation
	mod_R_bv<2048> := mod_N_bv = 0 ? 0 : mod_A_bv % mod_N_bv

	pushBV mod_R_bv
	popBN mod_R

	print mod_R

	return 0
end

replace <mbedtls_mpi_mod_int>(mod_R, mod_A, mod_iN) by
	# R = A mod N
	# R, A, N are mbedtls_mpi structure pointers

	print mod_A
	print mod_N

	pushBN mod_A
	popBV mod_A_bv<2048>

	
	mod_N_bv<2048> := uext2048 mod_iN

	# Modulo operation
	mod_R_bv<2048> := mod_N_bv = 0 ? 0 : mod_A_bv % mod_N_bv

	pushBV mod_R_bv
	popBN mod_R

	print mod_R

	return 0
end
