replace <mbedtls_mpi_sub_mpi>(sub_X, sub_A, sub_B) by
	# X = A - B
	# X, A, B are mbedtls_mpi structure pointers

	print sub_A
	print sub_B

	pushBN sub_A
	pushBN sub_B
	subBN
	popBN sub_X

	print sub_X

	return 0
end
