replace <mbedtls_mpi_shift_r>(shr_X, shr_count) by
	# X = X >> count (right shift)
	# X is mbedtls_mpi structure pointer
	# count is number of bits to shift

	print shr_X
	print shr_count

	pushBN shr_X
	shr_count_bv<2048> := uext2048 shr_count
	pushBV shr_count_bv
	rightUShiftBN
	popBN shr_X
	print shr_X
	return 0
end
