replace <br_i31_mulacc>(ma_d, ma_a, ma_b) by
	print ma_d
	print @[ma_d,4]
	print @[ma_d+4,0x84]
	print @[ma_a,4]
	print @[ma_a+4,0x84]
	print @[ma_b,4]
	print @[ma_b+4,0x84]
        pushBN ma_a
        #popBV ma_a_bv<1024>
        #print ma_a_bv
	pushBN ma_b
	mulBN
	pushBN ma_d
	addBN
	popBN ma_d
	
	print @[ma_d,4]
	print @[ma_d+4,0x84]
	return 0
end


glo_dec_x<32> := 0

hook <br_i31_decode>(dec_x, dec_src, dec_len) with
	print dec_x
	print @[dec_src, 0x20]
	print @[dec_src, 4]
	print @[dec_src+4, 4]
	print @[dec_src+8, 4]
	glo_dec_x := dec_x
end

hook 0x0804beeb with
	print glo_dec_x
	print @[glo_dec_x, 4]
	print @[glo_dec_x+4, 36]
	
end
