#add_a_glo<32> := 0

tmp_res<32> := 0x40000000

replace <br_i31_add>(add_a, add_b, add_ctl) by  # br_i31_add
		#add_a_glo := add_a

		#print add_ctl

		#print @[add_a, 4]
		#print (((@[add_a, 4] + 63) lsr 5)-1)
		#print @[add_a+4, 68]

		#print @[add_b, 4]
		#print ((@[add_b, 4] + 63) lsr 5)
		#print @[add_b+4, 68]
		pushBN add_a
		pushBN add_b
		addBN
		popBN tmp_res
		@[add_a+4, 68] := add_ctl = 0 ? @[add_a+4, 68] : @[tmp_res+4, 68]

		#print @[add_a+4, 68]
		#print carry32<32>

		return 1 #carry32
end

#reach * <br_i31_add:last> then print @[add_a_glo+4,68] and print eax
