replace <BN_mod_exp_mont>(modexp_rr, modexp_a, modexp_p, modexp_m, _, _) by
	#call_macro mk_safe(uadd_r)
	
	#@[modexp_a+4,4] := 0x2
	#@[@[modexp_a,4], 0x100] := 7
	#@[modexp_p+4,4] := 0x2
	#@[@[modexp_p,4], 0x100] := 0
	#@[modexp_m+4,4] := 0x2
	#@[@[modexp_m,4], 0x100] := 4 # 877 * 877 = 2908 * 877 = 2712 * 877 = 2169 * 877 = 1209
	#print modexp_a
	#print @[modexp_a, 4]
	print @[modexp_a+4, 4]
	print @[@[modexp_a, 4], 128]
	#print modexp_p
	#print @[modexp_p, 4]
	print @[modexp_p+4, 4]
	print @[@[modexp_p, 4], 128]
	#print modexp_m
	#print @[modexp_m, 4]
	print @[modexp_m+4, 4]
	print @[@[modexp_m, 4], 128]
	
	
	pushBN modexp_a
	popBV modexp_a_bv<2056>
	pushBN modexp_p
	popBV modexp_p_bv<2056>
	pushBN modexp_m
	popBV modexp_m_bv<2056>

        
	#print modexp_a_bv
	#print modexp_p_bv
	#print modexp_m_bv
	modexp_rr_bv<2056> := 1
	modexp_aa_bv<2056> := modexp_a_bv %u 0xe449a23c # modexp_m_bv


	for modexp_j<2056> in 0 to 2055 do
		modexp_i<2056> := 2055 - modexp_j  # 2047, 2046, ..., 0
		modexp_r2_bv<2056> := (modexp_rr_bv * modexp_rr_bv) %u 0xe449a23c # modexp_m_bv  # (r * r) % m 
		modexp_r3_bv<2056> := (modexp_r2_bv * modexp_aa_bv) %u 0xe449a23c # modexp_m_bv  # 
		bit<2056> := (modexp_p_bv lsr modexp_i) & 0x1
		mask<2056> := 0 - bit
		modexp_rr_bv := (modexp_r3_bv & mask) | (modexp_r2_bv & ~mask)
	end
	print modexp_rr_bv
	#for modexp_i<2056> in 1 to modexp_p_bv do
	#	modexp_rr_bv := modexp_pp_bv{0} = 1 ? (modexp_rr_bv * modexp_aa_bv) % modexp_m_bv : modexp_rr_bv
	#	modexp_aa_bv := (modexp_aa_bv * modexp_aa_bv) % modexp_m_bv
		
	#	#print modexp_rr_bv
	#end
	pushBV modexp_rr_bv 
	popBN modexp_rr
	
	
	
	#print @[modexp_rr, 4]
	#print @[modexp_rr+4, 4]
	#print @[@[modexp_rr, 4], 128]
	#halt
	return 1
end

replace <BN_mod_exp_mont_consttime>(modexp_rr, modexp_a, modexp_p, modexp_m, _, _) by
	#call_macro mk_safe(uadd_r)
	
	#@[modexp_a+4,4] := 0x2
	#@[@[modexp_a,4], 0x100] := 7
	#@[modexp_p+4,4] := 0x2
	#@[@[modexp_p,4], 0x100] := 0
	#@[modexp_m+4,4] := 0x2
	#@[@[modexp_m,4], 0x100] := 4 # 877 * 877 = 2908 * 877 = 2712 * 877 = 2169 * 877 = 1209
	#print modexp_a
	#print @[modexp_a, 4]
	print @[modexp_a+4, 4]
	print @[@[modexp_a, 4], 128]
	#print modexp_p
	#print @[modexp_p, 4]
	print @[modexp_p+4, 4]
	print @[@[modexp_p, 4], 128]
	#print modexp_m
	#print @[modexp_m, 4]
	print @[modexp_m+4, 4]
	print @[@[modexp_m, 4], 128]
	
	
	pushBN modexp_a
	popBV modexp_a_bv<2056>
	pushBN modexp_p
	popBV modexp_p_bv<2056>
	pushBN modexp_m
	popBV modexp_m_bv<2056>
	print @[@[modexp_m,4],256]
	print @[modexp_m+4,4]
	print @[modexp_m+12,4]
	#print modexp_a_bv
	#print modexp_p_bv
	print modexp_m_bv
        # modexp_m_bv := 0xe449a23c
        modexp_m_bv := modexp_m_bv = 0 ? modexp_m_bv+1 : modexp_m_bv
        # modexp_m_bv := modexp_m_bv lsl 992
	modexp_rr_bv<2056> := 1
	modexp_aa_bv<2056> := modexp_a_bv % modexp_m_bv
	
	for modexp_j<2056> in 0 to 2055 do
		modexp_i<2056> := 2055 - modexp_j  # 2047, 2046, ..., 0
		modexp_r2_bv<2056> := (modexp_rr_bv * modexp_rr_bv) % 0x2233 #% modexp_m_bv  # (r * r) % m 
		modexp_r3_bv<2056> := (modexp_r2_bv * modexp_aa_bv) % 0x2233 #% modexp_m_bv  # 
		bit<2056> := (modexp_p_bv lsr modexp_i) & 0x1
		mask<2056> := 0 - bit
		modexp_rr_bv := (modexp_r3_bv & mask) | (modexp_r2_bv & ~mask)
	end
	print modexp_rr_bv
	#for modexp_i<2056> in 1 to modexp_p_bv do
	#	modexp_rr_bv := modexp_pp_bv{0} = 1 ? (modexp_rr_bv * modexp_aa_bv) % modexp_m_bv : modexp_rr_bv
	#	modexp_aa_bv := (modexp_aa_bv * modexp_aa_bv) % modexp_m_bv
		
	#	#print modexp_rr_bv
	#end
	pushBV modexp_rr_bv 
	popBN modexp_rr
	
	
	
	#print @[modexp_rr, 4]
	#print @[modexp_rr+4, 4]
	#print @[@[modexp_rr, 4], 128]
	#halt
	return 1
end

hook <BN_mod_exp_mont_consttime_x2>(rr1, a1, p1, m1, inmon1, rr2, a2, p2, m2, _) with
	print @[@[a1,4], 128]
	print @[a1+4,4]
	print @[@[p1,4], 128]
	print @[p1+4,4]
	print @[@[m1,4], 128]
	print @[m1+4,4]
	print @[@[a2,4], 128]
	print @[@[p2,4], 128]
	print @[@[m2,4], 128]
end


