replace <BN_mod_mul_montgomery>(modmul_r, modmul_a, modmul_b, modmul_mont, _) by
	
	#computes Mont(a,b):=a*b*R^-1 and places the result in r.

	# Extract bvN = bignum_to_bv(mont->N)
	# Compute R=2^ri
	# Compute Rinv=(1+bvN∗bvNi)/R  mod  bvN
	# Compute:bvr=((bva∗bvb)∗Rinv)  mod bvN

	modmul_ri<32> := @[modmul_mont, 4]
	modmul_ri2<4096> := (2 lsl (uext4096 modmul_ri))
	
	modmul_N<32> := modmul_mont+24
	modmul_Ni<32> := modmul_mont+44
	
	pushBN modmul_N
	popBV modmul_N_bv<2048>
	modmul_N_bv2<4096> := uext4096 modmul_N_bv
	
	pushBN modmul_a
	popBV modmul_a_bv<2048>
	modmul_a_bv2<4096> := uext4096 (modmul_a_bv % modmul_N_bv)
	pushBN modmul_b
	popBV modmul_b_bv<2048>
	modmul_b_bv2<4096> := uext4096 (modmul_b_bv % modmul_N_bv)
	
	pushBN modmul_Ni
	popBV modmul_Ni_bv<2048>
	modmul_Ni_bv2<4096> := uext4096 modmul_Ni_bv
	bv_N_Ni2<4096> := (modmul_N_bv2 * modmul_Ni_bv2) + 1
	bv_N_Ni2 := bv_N_Ni2 / modmul_ri2
	bv_N_Ni2 := bv_N_Ni2 % modmul_N_bv2
	modmul_a_bv2 := (modmul_a_bv2 * modmul_b_bv2) % modmul_N_bv2
	bv_N_Ni2 := (modmul_a_bv2 * bv_N_NN2) % modmul_N_bv2  
	modmul_r_bv<2048> := bv_N_Ni2{2047..0}
	pushBV modmul_r_bv
	popBN modmul_r
	
	print modmul_r
	print @[modmul_r+4,4]
	
	return 1
end

replace <bn_mul_mont_fixed_top>(modmul_r, modmul_a, modmul_b, modmul_mont, _) by
	#computes Mont(a,b):=a*b*R^-1 and places the result in r.

	# Extract bvN = bignum_to_bv(mont->N)
	# Compute R=2^ri
	# Compute Rinv=(1+bvN∗bvNi)/R  mod  bvN
	# Compute:bvr=((bva∗bvb)∗Rinv)  mod bvN

	modmul_ri<32> := @[modmul_mont, 4]
	modmul_ri2<4096> := (2 lsl (uext4096 modmul_ri))
	
	modmul_N<32> := modmul_mont+24
	modmul_Ni<32> := modmul_mont+44
	
	pushBN modmul_N
	popBV modmul_N_bv<2048>
	modmul_N_bv2<4096> := uext4096 modmul_N_bv
	
	pushBN modmul_a
	popBV modmul_a_bv<2048>
	modmul_a_bv2<4096> := uext4096 (modmul_a_bv % modmul_N_bv)
	pushBN modmul_b
	popBV modmul_b_bv<2048>
	modmul_b_bv2<4096> := uext4096 (modmul_b_bv % modmul_N_bv)
	
	pushBN modmul_Ni
	popBV modmul_Ni_bv<2048>
	modmul_Ni_bv2<4096> := uext4096 modmul_Ni_bv
	bv_N_Ni2<4096> := (modmul_N_bv2 * modmul_Ni_bv2) + 1
	bv_N_Ni2 := bv_N_Ni2 / modmul_ri2
	bv_N_Ni2 := bv_N_Ni2 % modmul_N_bv2
	modmul_a_bv2 := (modmul_a_bv2 * modmul_b_bv2) % modmul_N_bv2
	bv_N_Ni2 := (modmul_a_bv2 * bv_N_NN2) % modmul_N_bv2  
	modmul_r_bv<2048> := bv_N_Ni2{2047..0}
	pushBV modmul_r_bv
	popBN modmul_r
	
	print modmul_r
	print @[modmul_r+4,4]
	
	
	return 1
end



