replace <br_i31_reduce>(red_x, red_a, red_m) by
	pushBN red_a
	popBV red_bva<1056>
	pushBN red_m
	popBV red_bvm<1056>
	#while red_bvm > 0 && red_bva >= red_bvm do
	#	red_bva := red_bva - red_bvm
	#end
	red_bvm := red_bvm = 0 ? 0 : red_bva % (red_bvm)
	print @[red_a,0x88]
	print @[red_x,0x88]
	#@[red_x,0x88] := @[red_a,0x88]
	pushBV red_bvm
	popBN red_x
	return 0
end
