replace <mbedtls_mpi_add_abs>(aa_X, aa_A, aa_B) by
	# X = |A| + |B|
	pushBN aa_A
	pushBN aa_B
	addBN
	popBN aa_X
	# Result is always positive
	@[aa_X+4, 2] := 1
	return 0
end

replace <mbedtls_mpi_sub_abs>(sa_X, sa_A, sa_B) by
	# X = |A| - |B| (requires |A| >= |B|)
	pushBN sa_A
	pushBN sa_B
	subBN
	popBN sa_X
	# Result is always positive
	@[sa_X+4, 2] := 1
	return 0
end
