replace <mbedtls_mpi_gcd>(gcd_G, gcd_A, gcd_B) by
	# G = GCD(A, B) via Euclidean algorithm
	pushBN gcd_A
	popBV gcd_a_bv<2048>
	pushBN gcd_B
	popBV gcd_b_bv<2048>
	gcd_x<2048> := gcd_a_bv
	gcd_y<2048> := gcd_b_bv
	for i<32> in 0 to 2047 do
		gcd_done<32> := (gcd_y = 0) ? 1 : 0
		gcd_temp<2048> := (gcd_y = 0) ? 0 : gcd_x % gcd_y
		gcd_x := gcd_done = 1 ? gcd_x : gcd_y
		gcd_y := gcd_done = 1 ? 0 : gcd_temp
	end
	pushBV gcd_x
	popBN gcd_G
	@[gcd_G+4, 2] := 1
	return 0
end
