replace <mbedtls_mpi_lset>(ls_X, ls_z) by
	# X = z (set to signed integer value)
	# z is mbedtls_mpi_sint (int32_t)
	# If z < 0, set sign to -1 and store |z|
	ls_neg<32> := ls_z < 0 ? 1 : 0
	ls_abs<32> := ls_neg = 1 ? (0 - ls_z) : ls_z
	ls_bv<2048> := uext2048 ls_abs
	pushBV ls_bv
	popBN ls_X
	@[ls_X+4, 2] := ls_neg = 1 ? -1 : 1
	return 0
end
