replace <mbedtls_mpi_get_bit>(gb_X, gb_pos) by
	pushBN gb_X
	popBV gb_bv<2048>
	gb_bit<2048> := (gb_bv lsr (uext2048 gb_pos)) & 0x1
	return gb_bit{31..0}
end

replace <mbedtls_mpi_set_bit>(sb_X, sb_pos, sb_val) by
	pushBN sb_X
	popBV sb_bv<2048>
	sb_mask<2048> := 1 lsl (uext2048 sb_pos)
	# Clear bit, then set if val=1
	sb_bv := (sb_bv & ~sb_mask) | (sb_val = 1 ? sb_mask : 0)
	pushBV sb_bv
	popBN sb_X
	return 0
end
