replace <BN_uadd>(uadd_r, uadd_a, uadd_b) by
        call_macro mk_safe(uadd_r)
        #call_macro mk_b_safe(uadd_r)
        
        
        pushBN uadd_a
	pushBN uadd_b
	addBN
	popBN uadd_r

        #print uadd_r
        #print @[uadd_r,4]
        #print @[uadd_r+4,4]
        #print @[uadd_r+8,4]
        #print @[uadd_r+12,8]
        #print @[@[uadd_r,4], 0x80]
	
	return 1
end
