replace <sp_div>(div_a, div_d, div_r, div_rem) by

        if div_r <> 0 then
           pushBN div_a
           popBV div_a_bv<2056>
           pushBN div_d
           popBV div_d_bv<2056>
           div_d_bv := div_d_bv = 0 ? div_d_bv + 1 : div_d_bv
           div_r_bv<2056> := div_a_bv / div_d_bv
           pushBV div_r_bv 
           popBN div_r

           print div_r
           print @[div_r, 5]
           print @[div_r+8, 0x100]
        end

        if div_rem <> 0 then
           pushBN div_a
           popBV div_a_bv<2056>
           pushBN div_d
           popBV div_d_bv<2056>
           div_d_bv := div_d_bv = 0 ? div_d_bv + 1 : div_d_bv
           div_rem_bv<2056> := div_a_bv % div_d_bv
           pushBV div_rem_bv 
           popBN div_rem

           print div_rem
           print @[div_rem, 5]
           print @[div_rem+8, 0x100]
        end
        
        return 0
end


replace <sp_mod>(mod_a, mod_m, mod_r) by

        #mod_bv_a<2048> := @[mod_a+8, 0x100]
        #mod_bv_m<2048> := @[mod_m+8, 0x100]

        #pushBV mod_bv_a
        #pushBV mod_bv_m
        
        pushBN mod_a
        popBV mod_a_bv<2056>
        pushBN mod_m
        popBV mod_m_bv<2056>
        mod_m_bv := mod_m_bv = 0 ? mod_m_bv + 1 : mod_m_bv
        mod_r_bv<2056> := mod_a_bv / mod_m_bv
        pushBV mod_r_bv 
        popBN mod_r

        print mod_r
        print @[mod_r, 2]
        print @[mod_r+8, 0x100]
        
        return 0
end
