replace <sp_count_bits>(cb_a) by
	pushBN cb_a
	popBV cb_bv<512>
	# Binary search for highest set bit (CT)
	btln<32> := 0
	bv<512> := cb_bv
	bv_p<512> := bv lsr 256
	btln := (bv_p = 0) ? btln : btln + 256
	bv := (bv_p = 0) ? bv : bv_p
	bv_p := bv lsr 128
	btln := (bv_p = 0) ? btln : btln + 128
	bv := (bv_p = 0) ? bv : bv_p
	bv_p := bv lsr 64
	btln := (bv_p = 0) ? btln : btln + 64
	bv := (bv_p = 0) ? bv : bv_p
	bv_p := bv lsr 32
	btln := (bv_p = 0) ? btln : btln + 32
	bv := (bv_p = 0) ? bv : bv_p
	bv_p := bv lsr 16
	btln := (bv_p = 0) ? btln : btln + 16
	bv := (bv_p = 0) ? bv : bv_p
	bv_p := bv lsr 8
	btln := (bv_p = 0) ? btln : btln + 8
	bv := (bv_p = 0) ? bv : bv_p
	bv_p := bv lsr 4
	btln := (bv_p = 0) ? btln : btln + 4
	bv := (bv_p = 0) ? bv : bv_p
	bv_p := bv lsr 2
	btln := (bv_p = 0) ? btln : btln + 2
	bv := (bv_p = 0) ? bv : bv_p
	bv_p := bv lsr 1
	btln := (bv_p = 0) ? btln : btln + 1
	btln := (cb_bv = 0) ? 0 : btln + 1
	return btln
end
