replace <mbedtls_mpi_add_mpi>(add_X, add_A, add_B) by
	# X = A + B
	# X, A, B are mbedtls_mpi structure pointers

	print add_A
	print add_B

	pushBN add_A
	pushBN add_B
	addBN
	popBN add_X

	print add_X

	return 0
end
