hook <sp_mulmod>(mul_a, mul_b, mul_m, mul_r) with
        pushBN mul_a
        popBV mul_a_bv<2056>
        pushBN mul_b
        popBV mul_b_bv<2056>
        pushBN mul_m
        popBV mul_m_bv<2056>
        print mul_a_bv
        print mul_b_bv
        print mul_m_bv
        # halt
end

glo_exm_r<32> := 0
glo_exm_m<32> := 0
glo_exm_e<32> := 0


hook <sp_exptmod_nct>(exm_b, exm_e, exm_m, exm_r) with
	print exm_b
	print exm_e
	print exm_m
	print exm_r
	glo_exm_r := exm_r
	glo_exm_m := exm_m
	glo_exm_e := exm_e
	
	print @[exm_b,5]
	print @[exm_e,5]
	print @[exm_m,5]
        print @[exm_b+8,0x100]
        print @[exm_e+8,0x100]
        print @[exm_m+8,0x100]
    	
        pushBN exm_m
        popBV exm_m_bv<2056>
    	exm_m_bv<2056> := (@[exm_m,2] = 0 || @[exm_m+4,1] = 1 ? 1 : exm_m_bv)
    	
    	pushBN exm_b
        popBV exm_b_bv<2056>
    
        pushBN exm_e
        popBV exm_e_bv<2056>
        
        #exm_b_bv := 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        #exm_m_bv := 0x1bbbbbbbbbbbbbbc
        #exm_e_bv := 0x1
        
        #pushBV exm_b_bv
        #popBN exm_b
        
        #pushBV exm_m_bv
        #popBN exm_m
        
        #pushBV exm_e_bv
        #popBN exm_e
        
        #print exm_b_bv
        #print exm_e_bv
        #print exm_m_bv
        
        @[exm_m+8,1] := @[exm_m+8,1] & 0xfe
        
        print @[exm_b, 0x108]
        print @[exm_e, 0x108]
        print @[exm_m, 0x108]
end


hook 0x0804f7af with
	print @[glo_exm_r, 5]
	print @[glo_exm_r+8,0x100]
	print @[glo_exm_m, 5]
	print @[glo_exm_m+8,0x100]
	print @[glo_exm_e, 5]
	print @[glo_exm_e+8,0x100]
	
end
